### ISSUE TITLE
Incorrect demangling of functions having ellipsis (three dots in the parameter list)

### ISSUE THREAD

**Issue by q1o1p** [avast-tl/demangler#1]
elliptic function like "?debugf@@YAXPB_WZZ" demangling wrong.
now: "void __cdecl debugf(wchar_t const *)"
must be: "void __cdecl debugf(wchar_t const *,...)"
lose '...'

**Comment by PeterMatula** [comment]
Thank you for the report.

However, we will not be able to fix this in the current implementation. See #2 and the newly added [Status](https://github.com/avast-tl/demangler#status) section in `README.md`.

Sorry we did not make this clear from the start.

**Comment by PeterMatula** [comment]
Moved to https://github.com/avast-tl/retdec/issues/96.
